/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { close_dialog_stack_top_T } from './close_dialog_stack_top_b.js'
import type { dialog_stack$_T } from './dialog_stack$_b.js'
import type { dialog_stack_top$_T } from './dialog_stack_top$_b.js'
export interface dialog_ctx_I {
	close_dialog_stack_top?:close_dialog_stack_top_T
	dialog_stack$?:dialog_stack$_T
	dialog_stack_top$?:dialog_stack_top$_T
}